[build]
jobs = 6 # number of parallel jobs, defaults to # of CPUs
target = [
    "x86_64-unknown-linux-gnu",
] # build for the target triple (ignored by `cargo install`)
target-dir = "target" # path of where to place all generated artifacts
incremental = true # whether or not to enable incremental compilation
rustc-wrapper = "/usr/local/bin/sccache"

[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

# Modify profile settings via config.
[profile.dev]
opt-level = 0           # Optimization level.
debug = true            # Include debug info.
debug-assertions = true # Enables debug assertions.
overflow-checks = true  # Enables runtime integer overflow checks.
lto = false             # Sets link-time optimization.
panic = 'unwind'        # The panic strategy.
incremental = true      # Incremental compilation.
codegen-units = 16      # Number of code generation units.
rpath = false           # Sets the rpath linking option.

[profile.release]
debug = true
incremental = true
lto = false
